WITH clean_data AS (
    SELECT
        _id AS _id,
        CAST(REPLACE(REPLACE(age, ',', ''), '.', '.') AS INTEGER) AS age,
        CAST(REPLACE(REPLACE(bmi, ',', ''), '.', '.') AS DECIMAL) AS bmi,
        CAST(REPLACE(REPLACE(bmr, ',', ''), '.', '.') AS DECIMAL) AS bmr,
        CAST(REPLACE(REPLACE(smi, ',', ''), '.', '.') AS DECIMAL) AS smi,
        time AS time,
        state AS state,
        CAST(REPLACE(REPLACE(bfmMax, ',', ''), '.', '.') AS DECIMAL) AS bfmMax,
        CAST(REPLACE(REPLACE(bfmMin, ',', ''), '.', '.') AS DECIMAL) AS bfmMin,
        CAST(REPLACE(REPLACE(bfpMax, ',', ''), '.', '.') AS DECIMAL) AS bfpMax,
        CAST(REPLACE(REPLACE(bfpMin, ',', ''), '.', '.') AS DECIMAL) AS bfpMin,
        CAST(REPLACE(REPLACE(bmiMax, ',', ''), '.', '.') AS DECIMAL) AS bmiMax,
        CAST(REPLACE(REPLACE(bmiMin, ',', ''), '.', '.') AS DECIMAL) AS bmiMin,
        CAST(REPLACE(REPLACE(bmrMax, ',', ''), '.', '.') AS DECIMAL) AS bmrMax,
        CAST(REPLACE(REPLACE(bmrMin, ',', ''), '.', '.') AS DECIMAL) AS bmrMin,
        CAST(REPLACE(REPLACE(height, ',', ''), '.', '.') AS DECIMAL) AS height,
        CAST(REPLACE(REPLACE(smmMax, ',', ''), '.', '.') AS DECIMAL) AS smmMax,
        CAST(REPLACE(REPLACE(smmMin, ',', ''), '.', '.') AS DECIMAL) AS smmMin,
        CAST(REPLACE(REPLACE(allBody, ',', ''), '.', '.') AS DECIMAL) AS allBody,
        CAST(REPLACE(REPLACE(boneMax, ',', ''), '.', '.') AS DECIMAL) AS boneMax,
        CAST(REPLACE(REPLACE(boneMin, ',', ''), '.', '.') AS DECIMAL) AS boneMin,
        CAST(handled AS BOOL) AS handled,
        CAST(REPLACE(REPLACE(leftArm, ',', ''), '.', '.') AS DECIMAL) AS leftArm,
        CAST(REPLACE(REPLACE(leftLeg, ',', ''), '.', '.') AS DECIMAL) AS leftLeg,
        bodyType AS bodyType,
        CAST(REPLACE(REPLACE(boneMass, ',', ''), '.', '.') AS DECIMAL) AS boneMass,
        CAST(REPLACE(REPLACE(muscleKg, ',', ''), '.', '.') AS DECIMAL) AS muscleKg,
        nickName AS nickName,
        owner_id AS owner_id,
        CAST(REPLACE(REPLACE(rightArm, ',', ''), '.', '.') AS DECIMAL) AS rightArm,
        CAST(REPLACE(REPLACE(rightLeg, ',', ''), '.', '.') AS DECIMAL) AS rightLeg,
        timezone AS timezone,
        CAST(REPLACE(REPLACE(weightkg, ',', ''), '.', '.') AS DECIMAL) AS weightkg,
        CAST(REPLACE(REPLACE(weightlb, ',', ''), '.', '.') AS DECIMAL) AS weightlb,
        CAST(REPLACE(REPLACE(weightst, ',', ''), '.', '.') AS DECIMAL) AS weightst,
        CAST(REPLACE(REPLACE(allBodykg, ',', ''), '.', '.') AS DECIMAL) AS allBodykg,
        CAST(REPLACE(REPLACE(rightLeg, ',', ''), '.', '.') AS DECIMAL) AS rightLeg,
        CAST(REPLACE(REPLACE(bodyScore, ',', ''), '.', '.') AS INTEGER) AS bodyScore,
        CASE
            WHEN SAFE_CAST(createdAt AS DATETIME) IS NOT NULL
                AND SAFE_CAST(createdAt AS DATETIME) <= CURRENT_DATETIME()
                AND SAFE_CAST(createdAt AS DATE) >= DATE '2021-05-13'
            THEN SAFE_CAST(createdAt AS DATETIME)
            ELSE NULL
        END AS createdAt,
        CASE
            WHEN SAFE_CAST(deletedAt AS DATETIME) IS NOT NULL
                AND SAFE_CAST(deletedAt AS DATETIME) <= CURRENT_DATETIME()
                AND SAFE_CAST(deletedAt AS DATE) >= DATE '2021-05-13'
            THEN SAFE_CAST(deletedAt AS DATETIME)
            ELSE NULL
        END AS deletedAt,
        electrode AS electrode,
        CAST(REPLACE(REPLACE(leftArmkg, ',', ''), '.', '.') AS DECIMAL) AS leftArmkg,
        CAST(REPLACE(REPLACE(leftLegkg, ',', ''), '.', '.') AS DECIMAL) AS leftLegkg,
        CAST(REPLACE(REPLACE(proteinKg, ',', ''), '.', '.') AS DECIMAL) AS proteinKg,
        CAST(REPLACE(REPLACE(smPercent, ',', ''), '.', '.') AS DECIMAL) AS smPercent,
        CAST(REPLACE(REPLACE(weightMax, ',', ''), '.', '.') AS DECIMAL) AS weightMax,
        CAST(REPLACE(REPLACE(weightMin, ',', ''), '.', '.') AS DECIMAL) AS weightMin,
        CAST(REPLACE(REPLACE(bfmControl, ',', ''), '.', '.') AS DECIMAL) AS bfmControl,
        CAST(REPLACE(REPLACE(ffmControl, ',', ''), '.', '.') AS DECIMAL) AS ffmControl,
        CAST(REPLACE(REPLACE(rightArmkg, ',', ''), '.', '.') AS DECIMAL) AS rightArmkg,
        CAST(REPLACE(REPLACE(rightLegkg, ',', ''), '.', '.') AS DECIMAL) AS rightLegkg,
        CAST(REPLACE(REPLACE(weightstlb, ',', ''), '.', '.') AS DECIMAL) AS weightstlb,
        CAST(REPLACE(REPLACE(bfmStandard, ',', ''), '.', '.') AS DECIMAL) AS bfmStandard,
        CAST(REPLACE(REPLACE(bfpStandard, ',', ''), '.', '.') AS DECIMAL) AS bfpStandard,
        CAST(REPLACE(REPLACE(bmiStandard, ',', ''), '.', '.') AS DECIMAL) AS bmiStandard,
        CAST(REPLACE(REPLACE(bmrStandard, ',', ''), '.', '.') AS DECIMAL) AS bmrStandard,
        CAST(REPLACE(REPLACE(bodyWaterKg, ',', ''), '.', '.') AS DECIMAL) AS bodyWaterKg,
        CAST(REPLACE(REPLACE(ffmStandard, ',', ''), '.', '.') AS DECIMAL) AS ffmStandard,
        isSupportHR AS isSupportHR,
        CAST(REPLACE(REPLACE(physicalAge, ',', ''), '.', '.') AS INTEGER) AS physicalAge,

        CAST(REPLACE(REPLACE(precisionKg, ',', ''), '.', '.') AS DECIMAL) AS precisionKg,
        CAST(REPLACE(REPLACE(precisionLb, ',', ''), '.', '.') AS DECIMAL) AS precisionLb,
        CAST(REPLACE(REPLACE(smmStandard, ',', ''), '.', '.') AS DECIMAL) AS smmStandard,
        CAST(REPLACE(REPLACE(temperature, ',', ''), '.', '.') AS DECIMAL) AS temperature,
        CAST(REPLACE(REPLACE(visceralFat, ',', ''), '.', '.') AS DECIMAL) AS visceralFat,
        CAST(REPLACE(REPLACE(weightGrama, ',', ''), '.', '.') AS DECIMAL) AS weightGrama,
        CAST(REPLACE(REPLACE(targetWeight, ',', ''), '.', '.') AS DECIMAL) AS targetWeight,
        CAST(REPLACE(REPLACE(waterMassMax, ',', ''), '.', '.') AS DECIMAL) AS waterMassMax,
        CAST(REPLACE(REPLACE(waterMassMin, ',', ''), '.', '.') AS DECIMAL) AS waterMassMin,
        CAST(REPLACE(REPLACE(allBodyMuscle, ',', ''), '.', '.') AS DECIMAL) AS allBodyMuscle,
        biologicalSex AS biologicalSex,
        bmiEvaluation AS bmiEvaluation,
        CAST(REPLACE(REPLACE(bodyFatMassKg, ',', ''), '.', '.') AS DECIMAL) AS bodyFatMassKg,
        CAST(REPLACE(REPLACE(leftArmmuscle, ',', ''), '.', '.') AS DECIMAL) AS leftArmmuscle,
        CAST(REPLACE(REPLACE(leftLegMuscle, ',', ''), '.', '.') AS DECIMAL) AS leftLegMuscle,
        CAST(REPLACE(REPLACE(muscleMassMax, ',', ''), '.', '.') AS DECIMAL) AS muscleMassMax,
        CAST(REPLACE(REPLACE(muscleMassMin, ',', ''), '.', '.') AS DECIMAL) AS muscleMassMin,
        CAST(REPLACE(REPLACE(musclePercent, ',', ''), '.', '.') AS DECIMAL) AS musclePercent,
        CAST(REPLACE(REPLACE(obesityDegree, ',', ''), '.', '.') AS DECIMAL) AS obesityDegree,
        CAST(REPLACE(REPLACE(precisionStlb, ',', ''), '.', '.') AS DECIMAL) AS precisionStlb,
        CAST(REPLACE(REPLACE(weightControl, ',', ''), '.', '.') AS DECIMAL) AS weightControl,
        CAST(REPLACE(REPLACE(bodyFatPercent, ',', ''), '.', '.') AS DECIMAL) AS bodyFatPercent,
        CAST(REPLACE(REPLACE(proteinMassMax, ',', ''), '.', '.') AS DECIMAL) AS proteinMassMax,
        CAST(REPLACE(REPLACE(proteinMassMin, ',', ''), '.', '.') AS DECIMAL) AS proteinMassMin,
        CAST(REPLACE(REPLACE(proteinPercent, ',', ''), '.', '.') AS DECIMAL) AS proteinPercent,
        CAST(REPLACE(REPLACE(rightArmMuscle, ',', ''), '.', '.') AS DECIMAL) AS rightArmMuscle,
        CAST(REPLACE(REPLACE(rightLegMuscle, ',', ''), '.', '.') AS DECIMAL) AS rightLegMuscle,
        CAST(REPLACE(REPLACE(weightStandard, ',', ''), '.', '.') AS DECIMAL) AS weightStandard,
        CAST(REPLACE(REPLACE(allBodyMusclekg, ',', ''), '.', '.') AS DECIMAL) AS allBodyMusclekg,
        CAST(REPLACE(REPLACE(kgScaleDivision, ',', ''), '.', '.') AS DECIMAL) AS kgScaleDivision,
        CAST(REPLACE(REPLACE(lbScaleDivision, ',', ''), '.', '.') AS DECIMAL) AS lbScaleDivision,
        CAST(REPLACE(REPLACE(leftArmMusclekg, ',', ''), '.', '.') AS DECIMAL) AS leftArmMusclekg,
        CAST(REPLACE(REPLACE(leftLegMusclekg, ',', ''), '.', '.') AS DECIMAL) AS leftLegMusclekg,
        CAST(REPLACE(REPLACE(moisturePercent, ',', ''), '.', '.') AS DECIMAL) AS moisturePercent,
        CAST(REPLACE(REPLACE(rightArmMusclekg, ',', ''), '.', '.') AS DECIMAL) AS rightArmMusclekg,
        CAST(REPLACE(REPLACE(rightLegMusclekg, ',', ''), '.', '.') AS DECIMAL) AS rightLegMusclekg,
        CAST(REPLACE(REPLACE(skeletalMuscleKg, ',', ''), '.', '.') AS DECIMAL) AS skeletalMuscleKg,
        bodyScoreEvaluation AS bodyScoreEvaluation,
        CAST(REPLACE(REPLACE(subcutaneousFatPercent, ',', ''), '.', '.') AS DECIMAL) AS subcutaneousFatPercent,
        muscleFatLeftArmEvaluation AS muscleFatLeftArmEvaluation,
        muscleFatLeftLegEvaluation AS muscleFatLeftLegEvaluation,
        muscleFatRightArmEvaluation AS muscleFatRightArmEvaluation,
        muscleFatRightLegEvaluation AS muscleFatRightLegEvaluation,
        muscleBalanceLeftArmEvaluation AS muscleBalanceLeftArmEvaluation,
        muscleBalanceLeftLegEvaluation AS muscleBalanceLeftLegEvaluation,
        muscleBalanceRightArmEvaluation AS muscleBalanceRightArmEvaluation,
        muscleBalanceRightLegEvaluation AS muscleBalanceRightLegEvaluation
    FROM {{ ref('bronze_weighins') }}
    WHERE SAFE_CAST(createdAt AS DATETIME) <= CURRENT_DATETIME()
    AND SAFE_CAST(deletedAt AS DATETIME) <= CURRENT_DATETIME()
)

SELECT * FROM clean_data
