version: 2

sources:
  - name: raw_data
    schema: data_warehouse  # Dataset onde os dados serão processados
    tables:
      - name: raw_tb_customer
       
      - name: raw_tb_customer_meal_plan
        
      - name: raw_tb_customer_medicines_prescriptions
        
      - name: raw_tb_customer_objectives
        
      - name: raw_tb_meal_plans
        
      - name: raw_tb_medicines
        
      - name: raw_tb_objectives
       
      - name: raw_tb_weighins
       