name: Deploy DAGs to GCS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: liti-case-analytics-engineer

    - name: Sincronizar DAGs com o GCS
      run: |
        gsutil -m rsync -r ./dags gs://airflow-dags-bucket-liti-case-analytics-engineer/dags
