# .github/workflows/deploy_dags.yml
name: Deploy DAGs to GCS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: liti-case-analytics-engineer
        export_default_credentials: true

    - name: Instalar gsutil
      run: |
        sudo apt-get update
        sudo apt-get install -y gsutil

    - name: Sincronizar DAGs com o GCS
      run: |
        gsutil -m rsync -r ./dags gs://airflow-dags-bucket-liti-case-analytics-engineer/dags

    - name: Limpar cache
      if: always()
      run: |
        gcloud auth revoke --all
